trigger:
  branches:
    include:
    - 'main'
    - 'dev'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: docker

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6 sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
- task: UseDotNet@2
  displayName: 'Use .NET 7 sdk'
  inputs:
    packageType: sdk
    version: 7.0.x
    includePreviewVersions: true # Required for preview versions


- script: dotnet restore
  displayName: "dotnet restore"
- script: dotnet build -c Release
  displayName: "dotnet build"

- script: docker build -f Dockerfile -t weihanli/dotnet-httpie:latest -t weihanli/dotnet-httpie:preview -t weihanli/dotnet-httpie:stable .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push weihanli/dotnet-httpie:latest
  displayName: 'Push docker image'

- script: |
    docker push weihanli/dotnet-httpie:preview
  displayName: 'Push latest image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

- script: docker push weihanli/dotnet-httpie:stable
  displayName: 'Push stable image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
