trigger:
  branches:
    include:
    - 'main'
    - 'preview'
    - 'dev'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: docker

steps:
- script: docker build -f Dockerfile -t weihanli/dotnet-httpie:latest -t weihanli/dotnet-httpie:preview -t weihanli/dotnet-httpie:stable .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push weihanli/dotnet-httpie:latest

- script: |
    docker push weihanli/dotnet-httpie:preview
  displayName: 'Push preview image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/preview'))

- script: |
    docker push weihanli/dotnet-httpie:stable
  displayName: 'Push stable image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
