trigger:
  branches:
    include:
    - 'main'
    - 'preview'
    - 'dev'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: docker

steps:
- script: |    
    docker version
    docker buildx version
    docker run --privileged --rm tonistiigi/binfmt --install all
    docker buildx create --name container-builder --driver docker-container --driver-opt default-load=true --bootstrap --use
  displayName: 'Setup qemu and docker buildx'

- script: docker buildx build -f Dockerfile --platform linux/amd64,linux/arm64,linux/arm -t weihanli/dotnet-httpie:latest -t weihanli/dotnet-httpie:preview -t weihanli/dotnet-httpie:stable .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push weihanli/dotnet-httpie:latest
  displayName: 'Push latest image'

- script: |
    docker push weihanli/dotnet-httpie:preview
  displayName: 'Push preview image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/preview'))

- script: |
    docker push weihanli/dotnet-httpie:stable
  displayName: 'Push stable image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
