trigger:
  branches:
    include:
    - 'main'
    - 'dev'
    - 'preview'

pool:
  vmImage: 'windows-latest'

variables:
- group: nuget

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6 sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
- task: UseDotNet@2
  displayName: 'Use .NET 7 sdk'
  inputs:
    packageType: sdk
    version: 7.0.x
- task: UseDotNet@2
  displayName: 'Use .NET 8 sdk'
  inputs:
    packageType: sdk
    version: 8.0.x
    includePreviewVersions: true # Required for preview versions

- script: dotnet --info
  displayName: "dotnet info"
- script: dotnet restore
  displayName: "dotnet restore"
- script: dotnet build -c Release
  displayName: "dotnet build"
- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    Nuget__ApiKey: $(nugetApiKey)
    Nuget__SourceUrl: $(nugetSourceUrl)

# Publish code coverage results v2
# Publish any of the code coverage results from a build.
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml" # string. Required. Path to summary files. 
