trigger:
  branches:
    include:
    - 'main'
    - 'dev'
    - 'preview'

pool:
  vmImage: 'windows-latest'

variables:
- group: nuget

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: sdk
    version: 10.0.x
    includePreviewVersions: true # Required for preview versions
- script: |
    dotnet tool install -g dotnet-execute
    dotnet-exec info
    dotnet --info
  displayName: "dotnet info"
- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    Nuget__ApiKey: $(nugetApiKey)
    Nuget__SourceUrl: $(nugetSourceUrl)

# Publish code coverage results v2
# Publish any of the code coverage results from a build.
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml" # string. Required. Path to summary files. 
