# Send request to get notice from reservation site
GET https://reservation.weihanli.xyz/api/notice

### SignIn

POST https://sparktodo.weihanli.xyz/api/v2/Account/SignIn
Content-Type: application/json; charset=utf-8

{
  "email": "weihanli@outlook.com",
  "password": "Test1234"
}
