name: release

on:
  push:
    branches:
      - main
      - dev
    
jobs:
  build-platform-specific:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            rid: linux-x64
          - os: ubuntu-24.04-arm
            rid: linux-arm64
          - os: windows-2025
            rid: win-x64
          - os: windows-11-arm
            rid: win-arm64
          - os: macos-15
            rid: osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: verify dotnet runtime-info
      run: dnx -y dotnet-execute info

    - name: Build AOT package for ${{ matrix.rid }}
      run: |
          dotnet publish src/HTTPie/HTTPie.csproj -f net10.0 --use-current-runtime -o artifacts/dist
          ls -R ./artifacts/dist 

    - name: Upload platform-specific package
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-http-${{ matrix.rid }}
        path: artifacts/dist/dotnet-httpie*
        retention-days: 10
        if-no-files-found: error

  release:
    needs: [build-platform-specific]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: dotnet info
      run: dnx -y dotnet-execute info
    - name: Export Release Version
      run: dnx -y dotnet-execute https://github.com/OpenReservation/scripts/blob/main/build/export-gh-release-version.cs
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
    - name: Create Github Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls -R ./dist
        gh release create ${{ env.ReleaseVersion }} --target main --generate-notes \
          ./dist/dotnet-http-linux-arm64/dotnet-httpie \
          ./dist/dotnet-http-linux-x64/dotnet-httpie \
          ./dist/dotnet-http-osx-arm64/dotnet-httpie \
          ./dist/dotnet-http-win-arm64/dotnet-httpie.exe \
          ./dist/dotnet-http-win-x64/dotnet-httpie.exe
