name: release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: dotnet info
      run: dotnet --info

    - name: Create Github release
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./build.ps1 --stable=true
        $VERSION = Get-ChildItem -Path artifacts/packages/*.nupkg -Name | Select-String -Pattern '\d+.\d+.\d+' | foreach {$_.Matches.Value}
        gh release create --generate-notes $VERSION
