name: release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: dotnet info
      run: |
        dotnet --info
        dotnet tool install -g dotnet-execute
        dotnet-exec info
    - name: Export Release Version
      run: dotnet-exec https://github.com/OpenReservation/scripts/blob/main/build/export-gh-release-version.cs
    - name: Create Github Release
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./build.ps1 --stable=true
        gh release create ${{ env.ReleaseVersion }} --generate-notes
